export let GET_MOOVIE_PENDING = "GET_MOOVIE_PENDING";
export let GET_MOOVIE_SUCCESS = "GET_MOOVIE_SUCCESS";
export let GET_MOOVIE_ERROR = "GET_MOOVIE_ERROR";

export let POST_MOOVIE_PENDING = "POST_MOOVIE_PENDING";
export let POST_MOOVIE_SUCCESS = "POST_MOOVIE_SUCCESS";
export let POST_MOOVIE_ERROR = "POST_MOOVIE_ERROR";

export let DELETE_MOOVIE_PENDING = "DELETE_MOOVIE_PENDING";
export let DELETE_MOOVIE_SUCCESS = "DELETE_MOOVIE_SUCCESS";
export let DELETE_MOOVIE_ERROR = "DELETE_MOOVIE_ERROR";

export let UPDATE_MOOVIE_PENDING = "UPDATE_MOOVIE_PENDING";
export let UPDATE_MOOVIE_SUCCESS = "UPDATE_MOOVIE_SUCCESS";
export let UPDATE_MOOVIE_ERROR = "UPDATE_MOOVIE_ERROR";